sudo: required
services:
  - docker
before_install:
  - docker build -t spaci1010/react-test -f ./client/Dockerfile.dev .
script:
  - docker run -e CI=true spaci1010/react-test npm run test --coverage

after_success:
  - docker build -t spaci1010/multi-client ./client
  - docker build -t spaci1010/multi-nginx ./nginx
  - docker build -t spaci1010/multi-server ./server
  - docker build -t spaci1010/multi-worker ./worker
